server:
  servlet:
    context-path: "/payments-app"
  port: 8989

spring:
  application:
    name: payments-core
  datasource:
    url: jdbc:postgresql://localhost:5432/JAVAPRO_DB
    password: 111
    username: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none